"""empty message

Revision ID: 49124e6ae006
Revises: 
Create Date: 2021-11-18 18:41:05.408996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49124e6ae006'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('school')
    op.drop_table('jobs')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('note_taker', sa.INTEGER(), nullable=False),
    sa.Column('hirer', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('date_complete', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['hirer'], ['user.id'], ),
    sa.ForeignKeyConstraint(['note_taker'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('school', sa.INTEGER(), nullable=True),
    sa.Column('document_name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['school'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
